SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES from REST_INFO R, (select FOOD_TYPE as C, MAX(FAVORITES) as FAVORITES2 from REST_INFO group by FOOD_TYPE) D
where R.FAVORITES = D.FAVORITES2 and R.FOOD_TYPE = D.C
order by FOOD_TYPE desc