SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) as "전체주소", CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8)) as TLNO from USED_GOODS_BOARD as b
join USED_GOODS_USER as u on b.WRITER_ID = u.USER_ID
group by USER_ID
HAVING USER_ID in (SELECT WRITER_ID from USED_GOODS_BOARD group by WRITER_ID having count(WRITER_ID) >= 3) 
order by USER_ID desc