-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME from ANIMAL_INS I
join ANIMAL_OUTS O on I.ANIMAL_ID = O.ANIMAL_ID
where SUBSTR(I.SEX_UPON_INTAKE, 1, 6) = 'Intact' and 
(SUBSTR(O.SEX_UPON_OUTCOME, 1, 6) = 'Spayed' or SUBSTR(O.SEX_UPON_OUTCOME, 1, 8) = 'Neutered')