WITH A AS(
SELECT year(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, S.USER_ID as USERS from USER_INFO U
join ONLINE_SALE S on U.USER_ID = S.USER_ID
where GENDER is not NULL
group by YEAR, MONTH, GENDER, S.USER_ID)

SELECT YEAR, MONTH, GENDER, count(USERS) AS USERS from A
GROUP BY YEAR, MONTH, GENDER
order by YEAR asc, MONTH asc, GENDER asc