SELECT (CASE WHEN MONTH(DIFFERENTIATION_DATE) <=3 then '1Q'
             WHEN MONTH(DIFFERENTIATION_DATE) <=6 then '2Q'
             WHEN MONTH(DIFFERENTIATION_DATE) <=9 then '3Q'
             WHEN MONTH(DIFFERENTIATION_DATE) <=12 then '4Q'
       END
       ) as QUARTER, COUNT(*) as ECOLI_COUNT from ECOLI_DATA
group by QUARTER
order by QUARTER
