SELECT USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES from USED_GOODS_USER, USED_GOODS_BOARD
where USER_ID = WRITER_ID and STATUS = 'DONE'
group by USER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES asc