-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR , abs(B.max_size - A.SIZE_OF_COLONY) as YEAR_DEV, A.ID from ECOLI_DATA A
left join (SELECT YEAR(DIFFERENTIATION_DATE) as year, MAX(SIZE_OF_COLONY) as max_size from ECOLI_DATA A
group by YEAR(DIFFERENTIATION_DATE)) B
on B.year = YEAR(A.DIFFERENTIATION_DATE)
order by YEAR, YEAR_DEV