-- 코드를 작성해주세요
select SUM(SCORE) as SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
    INNER JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO, YEAR
HAVING G.YEAR = '2022'
ORDER BY 1 DESC
LIMIT 1;
