select TITLE, U.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE from USED_GOODS_BOARD U
join USED_GOODS_REPLY R on U.BOARD_ID = R.BOARD_ID
where year(U.CREATED_DATE) = 2022 and month(U.CREATED_DATE) = 10
order by R.CREATED_DATE asc, U.TITLE asc;
